### ISSUE TITLE
Support secret chats via a user bot

### ISSUE THREAD

**Issue by NoamDev** [anvme/TONTgBot#2]
Such interface must be well protected.
Using a secret chat using a user bot, might help.

**Comment by anvme** [comment]
Telegram bots don't support secret chats

**Comment by NoamDev** [comment]
True, but using a user bot (i.e. a telegram's real user account controlled by a program) it can be done:)

**Comment by NoamDev** [comment]
@anvme You misunderstood my idea...
Why close so fast?
