### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by papanomad535** [anvme/TONTgBot#3]
$(HOME)tontgbot -> $(HOME)/tontgbot

I had to manually edit the file /etc/init.d/tontgbot to set the correct path

**Comment by anvme** [comment]
Hello!

 > $(HOME)tontgbot -> $(HOME)/tontgbot
Fixed, thank you
> I had to manually edit the file /etc/init.d/tontgbot to set the correct path
Path 4 in installation instruction has comments about it

**Comment by papanomad535** [comment]
There is no comment at the step 4 about to manually edit the file /etc/init.d/tontgbot - please check:

Open ./config.py in any editor and change values in TONTgBot from Edit starts here till Edit ends here. If you dont know your id(tg value), Just send message to @TONTgIDBot in telegram. Then open ./sbot.sh and put user folder at lines 14-15. Open ./tontgbot.service and put user&group at lines 7-8

**Comment by anvme** [comment]
>Then open ./sbot.sh and put user folder at lines 14-15
sbot.sh moved to /etc/init.d/tontgbot
Check it please
